AZURE_OPENAI_API_KEY="YOUR_API_KEY"
AZURE_OPENAI_ENDPOINT="YOUR_ENDPOINT"

AZURE_OPENAI_EMBEDDING_DEPLOYMENT="text-embedding-3-small"
AZURE_OPENAI_DEPLOYMENT="gpt-4o"
AZURE_OPENAI_REGION="eastus2"
OPENAI_API_VERSION="2024-05-01-preview"
